sudo: required

services:
  - docker

language: nodejs

before_install:
- docker build -t sitespeedio/sltc .

script:
- docker run --privileged --cap-add=ALL -v /lib/modules:/lib/modules sitespeedio/sltc

